# Variables
CC = gcc
FLAGS = -Wall -lm

# Archivos fuente y objeto
SRCS = lab2.c broker.c worker.c bmp.c filters.c fbroker.c fworker.c
OBJS = lab2.o broker.o worker.o bmp.o filters.o fbroker.o fworker.o

# Regla por defecto
all: lab2

# Regla para compilar el binario principal
lab2: $(OBJS)
	$(CC) -o lab2 $(OBJS) $(FLAGS)

# Reglas para compilar archivos objeto
lab2.o: lab2.c fbroker.h fworker.h
	$(CC) -c lab2.c $(FLAGS)

broker.o: broker.c fbroker.h
	$(CC) -c broker.c $(FLAGS)

worker.o: worker.c fworker.h
	$(CC) -c worker.c $(FLAGS)

bmp.o: bmp.c bmp.h
	$(CC) -c bmp.c $(FLAGS)

filters.o: filters.c filters.h
	$(CC) -c filters.c $(FLAGS)

fbroker.o: fbroker.c fbroker.h
	$(CC) -c fbroker.c $(FLAGS)

fworker.o: fworker.c fworker.h
	$(CC) -c fworker.c $(FLAGS)

# Limpiar archivos compilados
clean:
	rm -f lab2 $(OBJS)

.PHONY: all clean
